
IapiVersion: apps/v1
kind: Deployment
metadata:
  name: myq6app
spec:
  replicas: 3
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: myq6app
  template:
    metadata:
      labels:
        app: myq6app
    spec:
      containers:
      - name: myq6app
        image: shisdew/fluxq6:latest
        ports:
        - containerPort: 8080

